#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Decide how important it is for the user to see this message
PRIORITY=high

db_input $PRIORITY songscape/db_host || true
db_input $PRIORITY songscape/db_port || true
db_input $PRIORITY songscape/db_name || true
db_input $PRIORITY songscape/db_user || true
db_input $PRIORITY songscape/db_pass || true
db_input $PRIORITY songscape/servername || true
db_input medium songscape/use_snakeoil_certs || true
db_go
